### ISSUE TITLE
Data for Sensor Fusion in Table3

### ISSUE THREAD

**Issue by xiaolul2** [LiljaAdam/geographical-splits#2]
Nice work and thanks for pointing out the data leakage problem in Map construction tasks. 
I'm also a little confused about the evaluated data of camera and lidar fusions in Table 3 of your paper
![WechatIMG3838](https://github.com/LiljaAdam/geographical-splits/assets/43674104/059e8525-906a-4241-8a0c-0924e9230c19)
For MapTRV2, why is the result of multimodal fusion lower than that of single camera modality?

**Comment by LiljaAdam** [comment]
Thanks for your question. You are right, we were a bit surprised as well. 

We hypothesize that the hyperparameters in the official codebase are tuned to give the best results for camera-only. However, as we were only interested in the relative performance between Original and Geographical splits, and not the performance between using different sensor modalities, we let the hyperparameters remain unchanged.
